package com.java.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.ename
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.job_id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private Integer jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.mgr
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private Integer mgr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.joindate
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private Date joindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.salary
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.bonus
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private BigDecimal bonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.dept_id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.id
     *
     * @return the value of emp.id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.id
     *
     * @param id the value for emp.id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.ename
     *
     * @return the value of emp.ename
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.ename
     *
     * @param ename the value for emp.ename
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.job_id
     *
     * @return the value of emp.job_id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.job_id
     *
     * @param jobId the value for emp.job_id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.mgr
     *
     * @return the value of emp.mgr
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public Integer getMgr() {
        return mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.mgr
     *
     * @param mgr the value for emp.mgr
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setMgr(Integer mgr) {
        this.mgr = mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.joindate
     *
     * @return the value of emp.joindate
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public Date getJoindate() {
        return joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.joindate
     *
     * @param joindate the value for emp.joindate
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setJoindate(Date joindate) {
        this.joindate = joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.salary
     *
     * @return the value of emp.salary
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.salary
     *
     * @param salary the value for emp.salary
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.bonus
     *
     * @return the value of emp.bonus
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public BigDecimal getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.bonus
     *
     * @param bonus the value for emp.bonus
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setBonus(BigDecimal bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.dept_id
     *
     * @return the value of emp.dept_id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.dept_id
     *
     * @param deptId the value for emp.dept_id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}