package com.java.domain;

public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.jname
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private String jname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.description
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.id
     *
     * @return the value of job.id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.id
     *
     * @param id the value for job.id
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.jname
     *
     * @return the value of job.jname
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public String getJname() {
        return jname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.jname
     *
     * @param jname the value for job.jname
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setJname(String jname) {
        this.jname = jname == null ? null : jname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.description
     *
     * @return the value of job.description
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.description
     *
     * @param description the value for job.description
     *
     * @mbg.generated Thu Jun 20 21:21:13 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}